# Generated by Django 2.2.1 on 2019-05-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
